name: cargo
on: [pull request]
env:
  CARGO_TERM_COLOR: always

jobs:
  # check workspace for warnings & treat them as errors
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      -name: Install dev-dependencies
      run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1 
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --all-targets -- -D warnings

  # tests all crates in parallel
  test-lr_trie:
    name: test lr_trie
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./lr_trie/Cargo.toml

